### ISSUE TITLE
mqtt-smoker-probe question

### ISSUE THREAD

**Issue by stefan-armitage** [dshokouhi/Home-AssistantConfig#5]
Hello!
I'm gathering parts to build a copy of this, but i had a question. Would it be possible to use a MAX6682 instead of a MAX6675? I am thinking about using it together with a STC 1000 thermostat so i can get the temp to Home Assistant without having to use two different probes in the meat in my electrical smoker, and the STC 1000 uses an NTC sensor which the MAX6682 also uses.

**Comment by dshokouhi** [comment]
We would need to check the library, right now the library is specifically for the MAX6675. You can try checking out ESPHome too it may support it.

**Comment by stefan-armitage** [comment]
It did not seem too hard the flash a NodeMCU with ESPHome and get a temperature reading from an NTC sensor that way. Looked easier than changing your code, which i to be honest know nothing about. Thank you for pointing me in a good direction!

**Comment by dshokouhi** [comment]
Yea this code was done before ESPHome lol
